from django.http import HttpResponse


def index(request):
    a = "first line"
    b = "second line"
    c = "other line..."
    d1 = "variable"
    d2 = "variable"
    d3 = "variable"
    d4 = "variable"
    d5 = "variable"
    d6 = "variable"
    d7 = "variable"
    d8 = "variable"
    d9 = "variable"
    d1 = "variable"
    d2 = "variable"
    d3 = "variable"
    d4 = "variable"
    d5 = "variable"
    d6 = "variable"
    d7 = "variable"
    d8 = "variable"
    e9 = "variable"
    e4 = "variable"
    e5 = "variable"
    e6 = "variable"
    e7 = "variable"
    e8 = "variable"
    return HttpResponse("Hello, world. You're at the polls index.")


def other_index(request):
    a = "first line"
    b = "second line"
    c = "other line..."
    d1 = "variable"
    d2 = "variable"
    d3 = "variable"
    d4 = "variable"
    d5 = "variable"
    d6 = "variable"
    d7 = "variable"
    d8 = "variable"
    d9 = "variable"
    d1 = "variable"
    d2 = "variable"
    d3 = "variable"
    d4 = "variable"
    d5 = "variable"
    d6 = "variable"
    d7 = "variable"
    d8 = "variable"
    e9 = "variable"
    e4 = "variable"
    e5 = "variable"
    e6 = "variable"
    e7 = "variable"
    e8 = "variable"
    return HttpResponse("Hello, world. You're at the polls index.")